# Generated by Django 3.2.11 on 2022-02-15 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('get_user_name', models.CharField(max_length=10)),
                ('post_user_name', models.CharField(max_length=10)),
                ('topic', models.CharField(max_length=20)),
                ('content', models.CharField(max_length=300)),
                ('file', models.FileField(upload_to='file')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('get_user_delete', models.BooleanField(default=False)),
                ('post_user_delete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=10)),
                ('user_password', models.CharField(max_length=20)),
                ('user_phone_number', models.CharField(max_length=11)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
