# Generated by Django 3.2.11 on 2022-02-20 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_email_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='file',
            field=models.FileField(upload_to='file'),
        ),
    ]
